#!/usr/bin/env python2.7

import sys
import os
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, dev_path)

import datetime

import dmr.config.log
import dmr.config.dns
import dmr.db
import dmr.models.dns_messages

def _main():
    dm = dmr.models.dns_messages.DnsMessagesModel()

    now_dt = datetime.datetime.now()
    cutoff_dt = now_dt - datetime.timedelta(seconds=86400)
    
    rows = dm.get_daily_activity_by_hour(cutoff_dt)
    rows = sorted(
            rows, 
            key=lambda (timestamp_t, type_, count): (timestamp_t, type_))

    for (timestamp_t, type_, count) in rows:
        print('[{0}] [{1}]: ({2})'.format(timestamp_t, type_, count))

if __name__ == '__main__':
    _main()
