#!/usr/bin/env python2.7

import sys
import os
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import dmr.config.log

import dmr.db
import dmr.models.model_collection

def _provision():
    dmr.db.provision_db()

    for cls in dmr.models.model_collection.MODELS:
        o = cls()
        o.provision_tables()

_provision()
